export interface ManInteress {
    id: number,
    farm_name: string,
    proponent_name: string,
    province: string,
    county: string,
    village: string,
    condition: string,
    was_evaluated: boolean,
    observations: string,
    total_farm_area: number,
    pn_cultivation_area: number,
    total_project_cost: number,
    pdac_financing: string,
    bank_load: string,
    own_resources: string,
    statute: string,
    latitude: string,
    longitude: string,
    proposer: string,
    value_chain: string,
    created_at: any
}